apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgis-pv
  labels: 
    name: postgis-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data/postgis_pv"
  storageClassName: postgis-storage-class

