apiVersion: v1
kind: Service
metadata:
  name: auth-api-node-port
  labels:
    name: auth-api-node-port
spec:
  type: NodePort
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 31011
  selector:
    component: auth-api
    tier: protected