apiVersion: v1
kind: Service
metadata:
  name: geoserver-node-port
  labels:
    name: geoserver-node-port
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31003
  selector:
    component: geoserver
    tier: private