apiVersion: v1
kind: Service
metadata:
  name: geoserver-cluster-ip
  labels:
    name: geoserver-cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: geoserver
    tier: private
