apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port
  labels:
    name: nginx-node-port
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    component: nginx
    tier: public