apiVersion: v1
kind: Service
metadata:
  name: pgadmin-node-port
  labels:
    name: pgadmin-node-port
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001
  selector:
    component: pgadmin
    tier: public