apiVersion: v1
kind: Service
metadata:
  name: postgis-cluster-ip
  labels:
    name: postgis-cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    component: postgis
    tier: private
