apiVersion: v1
kind: Service
metadata:
  name: postgis-node-port
  labels:
    name: postgis-node-port
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
  selector:
    component: postgis
    tier: private
