apiVersion: v1
kind: Service
metadata:
  name: redisinsight-node-port
  labels:
    name: redisinsight-node-port
spec:
  type: NodePort
  ports:
    - port: 5540
      targetPort: 5540
      nodePort: 31002
  selector:
    component: redisinsight
    tier: public