apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    component: nginx
    tier: public
spec:
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        component: nginx
        tier: public
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      component: nginx
      tier: public


      
